image: alpine:latest

stages:
  - conclude

conclude:
  stage: conclude
  image: registry.infra.ifood-prod.com.br/ifood/platform-engineering/oss/github-check-updater:latest 
  variables: 
    REPOSITORY: batatinha-delivery/test-forks-pr
    SHA: ${CI_COMMIT_SHA}
  script:
    - cd /src
    - node check_success.js