include:
  - project: ifood/pipelines/gitlab-pipelines
    ref: ifood-security-1-stable
    file: pipelines/ifood-security/main.yml
stages:
  - .pre
  - test
  - security publish report
  - nowsecure
  - security publish nowsecure report
  - conclude


image: alpine:latest

conclude:
  stage: conclude
  image: registry.infra.ifood-prod.com.br/ifood/platform-engineering/oss/github-check-updater:latest 
  when: always
  variables: 
    REPOSITORY: batatinha-delivery/test-forks-pr
    SHA: ${CI_COMMIT_SHA}
  script:
    - cd /src
    - node check_success.js
